################################################################################
# gcc-target
################################################################################
GCC_TARGET_VERSION = $(GCC_VERSION)
GCC_TARGET_SITE = $(GCC_SITE)
GCC_TARGET_SOURCE = $(GCC_SOURCE)
GCC_TARGET_DEPENDENCIES = $(GCC_TARG_DEPENDENCIES) $(BR_LIBC)
GCC_TARGET_CONF_ENV = $(GCC_COMMON_CONF_ENV)
# out-of-tree build params
GCC_TARGET_SUBDIR = build
GCC_TARGET_PRE_CONFIGURE_HOOKS += GCC_CONFIGURE_SYMLINK
GCC_TARGET_EXTRACT_CMDS = $(GCC_EXTRACT_CMDS)
GCC_TARGET_POST_PATCH_HOOKS += GCC_APPLY_PATCHES
GCC_TARGET_LIBTOOL_PATCH = NO
GCC_TARGET_CONF_OPTS = \
	$(GCC_COMMON_CONF_OPTS) \
	$(GCC_GOOD_CONF_OPTS) \
	$(GCC_TARG_CONF_OPTS)
ifneq ($(call qstrip, $(BR2_XTENSA_CORE_NAME)),)
GCC_TARGET_POST_EXTRACT_HOOKS += HOST_GCC_XTENSA_OVERLAY_EXTRACT
endif
$(eval $(autotools-package))

